<script src="<?= base_url('assets/plugins/jquery/jquery.min.js') ?>"></script>
<script src="<?= base_url('assets/plugins/bootstrap/js/bootstrap.js') ?>"></script>
<script src="<?= base_url('assets/plugins/bootstrap-select/js/bootstrap-select.js') ?>"></script>
<script src="<?= base_url('assets/plugins/jquery-slimscroll/jquery.slimscroll.js') ?>"></script>
<script src="<?= base_url('assets/plugins/node-waves/waves.js') ?>"></script>
<script src="<?= base_url('assets/plugins/jquery-validation/jquery.validate.js') ?>"></script>
<script src="<?= base_url('assets/js/admin.js') ?>"></script>
<script src="<?= base_url('assets/js/ajax.js') ?>"></script>
<script src="<?= base_url('assets/js/pages/ui/tooltips-popovers.js') ?>"></script>
<script src="<?= base_url('assets/js/demo.js') ?>"></script>
<script src="<?= base_url('assets/js/pages/examples/sign-up.js') ?>"></script>
<script src="<?= base_url('assets/js/pages/examples/sign-in.js') ?>"></script>